/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 scene.gltf 
Author: lionarts3d (https://sketchfab.com/lionarts3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/abstract-figure-twist-de22538726ec4aef934b24ab69ed2c4d
Title: Abstract figure (twist)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export const Model = ({ props, modelRef }) => {
  const { nodes, materials } = useGLTF("/scene.gltf");
  return (
    <group ref={modelRef} {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          geometry={nodes.figure__figure__0.geometry}
          material={materials.figure}
          position={[0, 145.286, 0]}
        />
      </group>
    </group>
  );
};

useGLTF.preload("/scene.gltf");
